import katanaImage from "../images/katana.jpeg";

export const categories = [
  { id: 1, name: "Figürler", slug: "figurines", icon: "🗿", count: 24 },
  { id: 2, name: "Dekorasyon", slug: "decor", icon: "🏺", count: 18 },
  { id: 3, name: "Araç Gereç", slug: "tools", icon: "🔧", count: 12 },
  { id: 4, name: "Mimari", slug: "architecture", icon: "🏛️", count: 9 },
];

export const products = [
  {
    id: 1,
    name: "Ejderha Figürü",
    category: "figurines",
    price: 299,
    oldPrice: 399,
    material: ["PLA", "ABS"],
    colors: ["#1a1a1a", "#c0392b", "#2980b9"],
    image: katanaImage,
    rating: 4.8,
    reviews: 124,
    badge: "Çok Satan",
  },
  {
    id: 2,
    name: "Geometrik Vazo",
    category: "decor",
    price: 189,
    oldPrice: null,
    material: ["PETG"],
    colors: ["#ffffff", "#f5f5dc", "#2c3e50"],
    image: katanaImage,
    rating: 4.6,
    reviews: 87,
    badge: "Yeni",
  },
  {
    id: 3,
    name: "Masaüstü Organizer",
    category: "tools",
    price: 149,
    oldPrice: 199,
    material: ["PLA", "PETG"],
    colors: ["#ffffff", "#1a1a1a", "#27ae60"],
    image: katanaImage,
    rating: 4.9,
    reviews: 203,
    badge: "Çok Satan",
  },
  {
    id: 4,
    name: "Roma Sütunu",
    category: "architecture",
    price: 349,
    oldPrice: null,
    material: ["ABS"],
    colors: ["#f5f5dc", "#d4af37"],
    image: katanaImage,
    rating: 4.7,
    reviews: 56,
    badge: null,
  },
  {
    id: 5,
    name: "Mini Kaktüs Seti",
    category: "decor",
    price: 129,
    oldPrice: 159,
    material: ["PLA"],
    colors: ["#27ae60", "#2ecc71", "#f39c12"],
    image: katanaImage,
    rating: 4.5,
    reviews: 91,
    badge: "İndirim",
  },
  {
    id: 6,
    name: "Mekanik Kalp",
    category: "figurines",
    price: 249,
    oldPrice: null,
    material: ["PLA", "ABS"],
    colors: ["#c0392b", "#1a1a1a", "#bdc3c7"],
    image: katanaImage,
    rating: 4.9,
    reviews: 178,
    badge: "Yeni",
  },
];